---
title: "reading_data_from_the_web"
author: "Fang Liu"
date: "10/19/2021"
output: html_document
---

```{r eval=FALSE}
#tidyverse pacakge (dplyr, ggplot2, etc)
library(tidyverse)

#figure size options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#set theme settings
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load additional packages
```{r}
library(tidyverse)
library(rvest)
library(httr)
```

# NSDAH data
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = 
  read_html(url)

drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1) %>%  #slice out the first row (because of notes)
  view
```


# Star Wars 
{r load_starWar}
sw_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

sw_test = 
sw_html %>% 
  html_element(".lister-item-header a") %>% 
  html_text()

sw_df =
  tibble(
    title = sw_titles,
    revenue = sw_revenue
  )


```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

title_vec = 
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

# Napolean Dynamite
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = 
  read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars
)

reviews
```








